### ISSUE TITLE
UDP control doesn't accept negative numbers

### ISSUE THREAD

**Issue by joshctaylor** [asiermarzo/Ultraino#21]
The UDP control throws the following error when it receives a negative number from the place command:

Exception in thread "Thread-7" java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at acousticfield3d.math.Vector3f.parse(Vector3f.java:1200)
	at acousticfield3d.math.Vector3f.<init>(Vector3f.java:149)
	at acousticfield3d.gui.misc.UDPRemoteControl$3.run(UDPRemoteControl.java:134)
	at java.lang.Thread.run(Thread.java:748)

command string is in the following format.
"place 0 -0.019  0.115  0.007"

Code to create error using matlab:

u = udp('127.0.0.1',8085);
fopen(u);
fwrite(u,'clear');
fwrite(u,'create 1');
fwrite(u,'update');
write(u, 'place 0 -0.02  0.12 0.00');
fclose(u);

**Comment by joshctaylor** [comment]
I'll look more into it tomorrow, i found the error was caused by negative numbers on the place command. I updated the issue :)

**Comment by joshctaylor** [comment]
This was a bug in matlab caused by num2str adding an extra space:

```
>> num2str([0.0200    0.1150    0.0000], '%1.4f ')
ans =
    '0.0200 0.1150 0.0000'

>> num2str([0.0200    0.1150   -0.0003], '%1.4f ')
ans =
    '0.0200  0.1150 -0.0003'
```

This is solved using sprintf and removing the last space:
```
str = sprintf('%1.4f ', [0.0200    0.1150   -0.0003]);
str = str(1:end-1)
```
