### ISSUE TITLE
Running Ultraino Software on the Raspberry Pi

### ISSUE THREAD

**Issue by TechTerrier965** [asiermarzo/Ultraino#32]
I am having some troubles trying to get AcousticFieldSim to run though NetBeans on the Raspberry Pi. I am using a Raspberry Pi 4B 2gb, thats running Raspberry Pi OS (64bit), with the aarch64 processor. When NetBeans tries to run AcousticFieldSim, there is a slew of missing library errors. Ive added a JAR file called "gluegen-rt-natives-linux-aarch64.jar" to /home/pi/Desktop/Ultraino-2.5.0/Ultraino-2.5.0/AcousticFieldSim/jars , which fixed the first error message. Now I am getting a new error:

 `Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: 'boolean jogamp.common.jvm.JVMUtil.initialize(java.nio.ByteBuffer)'
	at jogamp.common.jvm.JVMUtil.initialize(Native Method)
	at jogamp.common.jvm.JVMUtil.<clinit>(JVMUtil.java:58)
	at com.jogamp.common.os.Platform$1.run(Platform.java:324)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
	at com.jogamp.opengl.GLProfile.<clinit>(GLProfile.java:154)
	at acousticfield3d.gui.MainForm.<init>(MainForm.java:137)
	at acousticfield3d.AcousticField3D.lambda$main$0(AcousticField3D.java:59)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

Is this an issue with AcousticFieldSim, or with JOGL/GLUEGEN? I have found an archived bug report with a similar error message, which I will link below. I have limited experience with Java or Github, so any help would be much appreciated.

https://www.mail-archive.com/debian-bugs-closed@lists.debian.org/msg363666.html

**Comment by kevinlinxc** [comment]
Your post helped me a lot (informing me to install Jars), I'm trying to run on my M2 Macbook.

I needed to download a bunch of jars from [https://jogamp.org/deployment/jogamp-current/jar/](https://jogamp.org/deployment/jogamp-current/jar/)
to Ultraino/AcousticFieldSim/jars/. There were already some jars in that folder, I'm guessing they were made for x86 architecture so they needed to be replaced.

Specifically, I downloaded the following jars:
1. [gluegen-rt-natives-macosx-universal.jar](https://jogamp.org/deployment/jogamp-current/jar/gluegen-rt-natives-macosx-universal.jar) (fixes "Can't load library … libgluegen_rt.dylib")
2. [jogl-all-natives-macosx-universal.jar](https://jogamp.org/deployment/jogamp-current/jar/jogl-all-natives-macosx-universal.jar) (fixes "nativewindow_awt" problem)
3. [jogl-all.jar](https://jogamp.org/deployment/jogamp-current/jar/jogl-all.jar) (fixes "jogamp.opengl.macosx.cgl.CGL.updateContext(J)V")
4. [gluegen-rt.jar](https://jogamp.org/deployment/jogamp-current/jar/gluegen-rt.jar) (fixes "Java.lang.NoSuchMethodError: com.jogamp.common.util.SecurityUtil.doPrivileged(Ljava/security/PrivilegedAction;)Ljava/lang/Object;")


After all that, the sim ran on my Macbook

@TechTerrier965  since your problem is still an UnsatisfiedLinkError issue, I feel like downloading more JARs might help you still.
